
// AccessToken --eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmY0ZjliMzUyZWMyY2IyM2FiNzVkMiIsImlhdCI6MTc1MjEyNTMzOX0.Su876Rdu2hkpRrUgm5sXIsHslKYlZG52rgVFKrhrouc
//POST http://localhost:3000/signup
//Content-Type:application/json

//{
//    "fullname":"john",
 //   "email":"john@gmail.com",
 //   "password":"John@123"
//}

# POST   https://leafy-zbvi.vercel.app/signin
# Content-Type: application/json

# {
#     "fullname":"Saurabh",
#     "email":"Saurabh@gmail.com",
#     "password":"Saurabh@123"
# }
POST   https://leafy-zbvi.vercel.app/signin
Content-Type: application/json

{
    "email":"Saurabh@gmail.com",
    "password":"Saurabh@123"
}